baseURL = "https://weekinmemes.netlify.app"
languageCode = "en-us"
title = "Week In Memes - What's Going Viral in India?"

theme = "onepress"
googleAnalytics = "UA-132703841-1"
disqusShortname = "weekinmemes"
enableEmoji = true
enableRobotsTXT = true
paginate = 10
enableGitInfo = true

[params]
header = "Week In Memes"
shareButton = true
description = "A blog to keep track of memes, videos, GIFs that are going viral in India and why."
widgets = true
twitter = "WeekInMemes"
facebook = "weekinmemes"
instagram = "weekinmemes"
linkedin = "weekinmemes"
pinterest = "dk_weekinmemes"
redbubble = "weekinmemes"
youtube = "UCnv6AphNCvg9j2FpwuBubiQ"
opengraphImage = "img/logo/6.jpg"
logo = "img/logo.jpg"
email = "dk@weekinmemes.com"
subscribeLink = "subscribe"
enableRSS = true

[services.instagram]
# appId = "754686758815876"
# clientToken = "52d217f906b402e3ab7114c6e0321019"
accessToken = "754686758815876|52d217f906b402e3ab7114c6e0321019"


[taxonomies]
tag = "tags"

[paginator]

[markup.goldmark.renderer]
unsafe= true
